# Generated by Django 5.2 on 2025-04-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('admin', 'Admin User')], default='user', max_length=10),
        ),
    ]
